env:
  es2021: true
  node: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules: {
  'no-console': 'off',
  import/extensions: [0, { <js>: "always" }],
  "no-underscore-dangle":  ["error", { "allow": ["_place"] }]
}
